export const DAILY_OPERATOR_REQUIRED_PERMISSIONS = [
  "tool:schedule.list",
  "tool:schedule.create",
  "tool:schedule.update",
  "tool:schedule.delete",
  "schedule:read",
  "schedule:create",
  "schedule:update",
  "schedule:delete",
  "tool:gmail.read",
  "tool:google.calendar.read",
  "tool:google.drive.read",
  "tool:gmail.write",
  "tool:google.calendar.write",
  "tool:google.drive.write",
  "network:googleapis.com",
  "secrets:GOOGLE_ACCESS_TOKEN",
  "secrets:GMAIL_ACCESS_TOKEN",
  "secrets:GOOGLE_CALENDAR_ACCESS_TOKEN",
  "secrets:GOOGLE_DRIVE_ACCESS_TOKEN",
  "google:gmail.read",
  "google:calendar.read",
  "google:drive.read",
  "google:gmail.write",
  "google:calendar.write",
  "google:drive.write",
  "channel:send",
  "external:send",
  "email:send",
] as const;

export const DEVELOPER_OPERATOR_REQUIRED_PERMISSIONS = [
  "tool:file.search",
  "fs:read",
  "tool:file.write",
  "tool:file.edit",
  "fs:write",
  "tool:github.read",
  "tool:github.write",
  "network:github.com",
  "secrets:GITHUB_TOKEN",
  "github:issue.write",
  "github:pr.write",
  "github:comment.write",
  "tool:browser.snapshot",
  "tool:browser.automation",
  "browser:snapshot",
  "browser:act",
  "network:http",
  "tool:shell.exec",
  "shell:exec",
] as const;

export const WRITING_OPERATOR_REQUIRED_PERMISSIONS = [
  "tool:file.search",
  "fs:read",
  "tool:file.write",
  "tool:file.edit",
  "fs:write",
  "tool:gmail.write",
  "tool:google.drive.write",
  "network:googleapis.com",
  "secrets:GOOGLE_ACCESS_TOKEN",
  "secrets:GMAIL_ACCESS_TOKEN",
  "secrets:GOOGLE_DRIVE_ACCESS_TOKEN",
  "google:gmail.write",
  "google:drive.write",
  "external:send",
  "email:send",
] as const;
